# Generated by Django 3.2.3 on 2021-05-19 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_cls',
        ),
    ]
